export const TEMPLATES = {
  viral: {
    id: 'viral',
    name: 'Viral Kick',
    headlineBg: '#FFFFFF',
    headlineFg: 'black',
    bar: true,
    blur: 22,
    darken: 0.18,
    captions: 'bold-viral',
  },
  clean: {
    id: 'clean',
    name: 'Clean',
    headlineBg: '#FFFFFF',
    headlineFg: 'black',
    bar: true,
    blur: 18,
    darken: 0.12,
    captions: 'clean-white',
  },
  news: {
    id: 'news',
    name: 'News',
    headlineBg: '#F4F4F5',
    headlineFg: 'black',
    bar: true,
    blur: 20,
    darken: 0.2,
    captions: 'clean-white',
  },
  meme: {
    id: 'meme',
    name: 'Meme',
    headlineBg: '#FFFFFF',
    headlineFg: 'black',
    bar: true,
    blur: 24,
    darken: 0.15,
    captions: 'bold-viral',
  },
  gaming: {
    id: 'gaming',
    name: 'Gaming',
    headlineBg: '#0B1220',
    headlineFg: 'white',
    bar: true,
    blur: 20,
    darken: 0.22,
    captions: 'gaming',
  },
  podcast: {
    id: 'podcast',
    name: 'Podcast',
    headlineBg: '#FFFFFF',
    headlineFg: 'black',
    bar: true,
    blur: 16,
    darken: 0.1,
    captions: 'karaoke',
  },
  cinematic: {
    id: 'cinematic',
    name: 'Cinematic',
    headlineBg: '#000000',
    headlineFg: 'white',
    bar: false,
    blur: 28,
    darken: 0.28,
    captions: 'minimal',
  },
  custom: {
    id: 'custom',
    name: 'Custom',
    headlineBg: '#FFFFFF',
    headlineFg: 'black',
    bar: true,
    blur: 22,
    darken: 0.18,
    captions: 'bold-viral',
  },
}

export function getTemplate(id) {
  return TEMPLATES[id] || TEMPLATES.viral
}
